name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for Web
      run: dotnet restore HMS/Web/Web.csproj
    - name: Restore dependencies for Core
      run: dotnet restore HMS/Core/Core.csproj
    - name: Restore dependencies for Application
      run: dotnet restore HMS/Application/Application.csproj
    - name: Restore dependencies for Infrastructure
      run: dotnet restore HMS/Infrastructure/Infrastructure.csproj

    - name: Build Web
      run: dotnet build HMS/Web/Web.csproj --no-restore
    - name: Build Core
      run: dotnet build HMS/Core/Core.csproj --no-restore
    - name: Build Application
      run: dotnet build HMS/Application/Application.csproj --no-restore
    - name: Build Infrastructure
      run: dotnet build HMS/Infrastructure/Infrastructure.csproj --no-restore

    - name: Test Web
      run: dotnet test HMS/Web/Web.csproj --no-build --verbosity normal
    - name: Test Core
      run: dotnet test HMS/Core/Core.csproj --no-build --verbosity normal
    - name: Test Application
      run: dotnet test HMS/Application/Application.csproj --no-build --verbosity normal
    - name: Test Infrastructure
      run: dotnet test HMS/Infrastructure/Infrastructure.csproj --no-build --verbosity normal